[OT103-98] Feat
alkemyTech/OT103-Client pull request #100
Opened 2021-12-10 14:49 UTC by JulianKominovic

**Tarea: agregar loading y alertas de Actividades.**

2021-12-11 18:41 UTC, FlaviaCohen requested changes

2021-12-11 18:41 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
>              return <ActivityCard key={activity.id} activity={activity} />;
Sería mejor aplicar el skeleton en el componente ActivityCard y que este maneje un estado interno. Si tiene todos los datos cargados que los devuelva, sino que devuelva un skeleton. De esta manera te asegurás de que el skeleton funcione realmente como un placeholder de componente mientras espera los datos. Para probar como queda podés ponerle un setTimeout que cambie el estado "loading" de la ActivityCard de true a false para que se llegue a ver el skeleton.

2021-12-12 19:23 UTC, JulianKominovic commented
Cree un custom skeleton para las cards de la lista de actividades y para la info de la actividad.

2021-12-13 12:18 UTC, FlaviaCohen requested changes
El skeleton debería ser uno solo y por props deberìa cambiar dinámicamente su contenido

2021-12-13 12:18 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +          <ActivityCard />
Acá me parece que es el <Skeleton/> lo que querés devovler

2021-12-13 12:18 UTC, FlaviaCohen commented on src/Components/Activities/ActivityCard.jsx
> +          <ActivityCardSkeleton variant="list" />
Hay 2 skeletons distintos?

2021-12-13 12:18 UTC, FlaviaCohen commented on src/Components/Activities/Detail/ActivityInfo.jsx
> +        <ActivitySkeleton variant="info" />
Mismo comentario

2021-12-13 14:42 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +          <ActivityCard />
Perdón..cualqueir cosa escribí. "...que es el skeleton" quise decir

2021-12-13 15:02 UTC, JulianKominovic commented
Timeout agregado

2021-12-13 17:58 UTC, JulianKominovic commented
Skeleton listo Fla, ahora si!

2021-12-13 18:41 UTC, FlaviaCohen requested changes

2021-12-13 18:41 UTC, FlaviaCohen commented on src/Components/Activities/ActivityCard.jsx
> +  const [loading, setLoading] = useState(false);
inicializá el loading en true para que no pase eso que mostraste hoy en la demo de que se ve la imagen y luego el skeleton.

2021-12-13 19:38 UTC, JulianKominovic commented
Hecho! Mil gracias!

2021-12-14 02:52 UTC, FlaviaCohen requested changes

2021-12-14 02:52 UTC, FlaviaCohen commented on src/Components/Activities/ActivityCard.jsx
>      setLoading(true);
si el estado inicial de loading es true ya no hace falta la lìnea 9 que lo setea en true de nuevo, dejemos sólo el setTimeout

2021-12-14 16:02 UTC, JulianKominovic commented
Arreglado

2021-12-15 02:27 UTC, FlaviaCohen approved these changes

2021-12-15 02:27 UTC, merged