[OT103-103] Feat
alkemyTech/OT103-Client pull request #105
Opened 2021-12-11 00:26 UTC by JulianKominovic

Tarea: Mostrar errores cuando las peticiones no se realicen correctamente EN CONTACTOS

2021-12-11 18:49 UTC, FlaviaCohen requested changes

2021-12-11 18:49 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +          <div className="activities__list gap-20px">
Misma corrección que el otro PR

2021-12-12 19:25 UTC, JulianKominovic commented
Arreglado!

2021-12-13 12:23 UTC, FlaviaCohen requested changes

2021-12-13 12:23 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +          <ActivityCard />
Misma correción que el otro PR, no estaràs queriendo devolver el Skeleton?

2021-12-13 14:44 UTC, FlaviaCohen requested changes
No se solucionaron los cambios requeridos

2021-12-13 15:02 UTC, JulianKominovic commented
Timeout agregado

2021-12-13 15:13 UTC, FlaviaCohen approved these changes

2021-12-13 15:14 UTC, merged