[OT103-57] Feat
alkemyTech/OT103-Client pull request #11
Opened 2021-11-25 16:38 UTC by JulianKominovic

Ahi subo el componente para renderizar las actividades.

Ojo que agregue la libreria react-icons

**En la carpeta helpers** ademas agrego una funcion simple que transforma de fecha que viene desde la API a un objeto que te devuelve la fecha y la hora.

2021-11-25 22:40 UTC, FlaviaCohen requested changes

2021-11-25 22:40 UTC, FlaviaCohen commented on src/Components/Title/Title.js
> +      <h1 style={{ textAlign: "center" }}>{title}</h1>
No entiendo muy bien que quiciste hacer con ese condicional. 
Por otro lado el atributo style no es buena práctica. Mejor importar una hoja de estilo y crear una clase.

2021-11-25 22:44 UTC, JulianKominovic commented on src/Components/Title/Title.js
> +      <h1 style={{ textAlign: "center" }}>{title}</h1>
No es mio eso Fla, por eso lo habia puesto a Lucas como reviewer, creo que el PR de el esta abierto todavia y yo pullee desde su branch para usar el componente.

2021-11-26 00:30 UTC, JulianKominovic commented
Errores corregidos!

2021-11-26 22:03 UTC, JulianKominovic commented
Main pulleado, todo listo, tuve que borrar el App.js para que no de conflictos

2021-11-28 02:31 UTC, FlaviaCohen approved these changes

2021-11-28 02:34 UTC, FlaviaCohen approved these changes

2021-11-28 02:34 UTC, merged