[OT103-115] Feat
alkemyTech/OT103-Client pull request #112
Opened 2021-12-13 19:44 UTC by JulianKominovic

**Tarea: Integrar Leaflet Maps en screen "Contacto".**

2021-12-14 03:07 UTC, FlaviaCohen requested changes

2021-12-14 03:07 UTC, FlaviaCohen commented on src/Components/Activities/ActivityCard.jsx
> +  useEffect(() => {
mismo comentario que en el otro PR, la línea 9 podemos sacarla

2021-12-14 03:07 UTC, FlaviaCohen commented on src/styles/components/mapStyles.scss
> +.leaflet-popup-content-wrapper {
No se donde estás usando esta clase pero acá popup es otro bloque, entonces la clase debería ser directamente popup__wrapper, popup__container, popup__button-close (porque el elemento es un botón y el modificador es "cerrar"), etc.

2021-12-14 16:00 UTC, JulianKominovic commented on src/styles/components/mapStyles.scss
> +.leaflet-popup-content-wrapper {
Es una clase interna de la libreria Leaflet

2021-12-15 02:29 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-15 15:36 UTC, JulianKominovic commented
conflicts fixed

2021-12-16 02:57 UTC, FlaviaCohen approved these changes

2021-12-16 02:57 UTC, merged