[OT-103]-132
alkemyTech/OT103-Client pull request #113
Opened 2021-12-14 00:17 UTC by decdabo

Cambios en el SliderCarouselComponent e implementación del School Campaign y sus estilos mobiles y pc

2021-12-14 03:23 UTC, FlaviaCohen requested changes

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Content.js
> +          <strong className="HS-campaign__content-countdown fs-2">
yo simplificaría un poco el nombre de esta clase y las que deriban. campaign__countdown (porque es probable que todas las campañas tengan el mismo estilo entonces no sería necesario especificar cual es), campaign__container, campaign__img, etc

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Content.js
> +            className="HS-campaign__content-img countdown-img-left"
acá si consideramos que countdown es un bloque la clase debería ser countdown__img-left

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Content.js
> +          <div className="HS-campaign__content-countdown-main">
este podrìa ser countdown__container

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Content.js
> +            className="HS-campaign__content-img countdown-img-right "
campaign__img y countdown__img-right

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Footer.js
> +    <footer className="HS-campaign__footer-container">
acá lo mismo: campaign__footer

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Footer.js
> +      <div className="HS-campaign__footer-logo-container">
y footer ya es otro bloque que podemos anidar dentro de campaign__footer para que no colisione. 

entonces quedaría así: 

```
.campaign{
    &__footer{
    ...

    .footer {
    ...
        &__img {
        ....
        }
        &__links{
        ...
        }
    }
    }
}
```

2021-12-14 03:23 UTC, FlaviaCohen commented on src/Campaigns/School/Header.js
> +    <header className="HS-campaign__header-container">
Misma corrección con el comentario anterior

2021-12-14 03:23 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +  const [loading, setLoading] = useState(false);
estado inicial del loading debería ser true ya que sino pasa lo que comentaba Julián hoy de que se ve primero la imagen, luego la carga y luego nuevamente la imagen.

2021-12-14 03:23 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +      setLoading(true);
de paso te ahorrás esta línea porque el loading ya inicializa en true

2021-12-14 03:23 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
> +    .HS-campaign__content-{
La idea de que el estilo sea mobile-first es que la pantalla mobile sea la default, por ende declarás los estilos sin media query como querrías que se vea en celular y solo adaptás para las pantallas más grandes

2021-12-14 11:16 UTC, decdabo commented on src/Campaigns/School/Content.js
> +          <strong className="HS-campaign__content-countdown fs-2">
pasa que es campaign y el content es por el componente contenido por eso creo que me quedo con campaign__content-<elemento />

2021-12-14 15:10 UTC, FlaviaCohen commented on src/Campaigns/School/Content.js
> +          <strong className="HS-campaign__content-countdown fs-2">
es que content no es el elemento. Método BEM, bloque__elemento-modificador, definir content como elemento es incorrecto

2021-12-15 14:48 UTC, FlaviaCohen requested changes

2021-12-15 14:48 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
> +    .campaign__{
la tarjeta pide que el estilo sea mobile-first, eso quiere decir que los estilos por default van a estar pensado para resolución chica y las media queries que se usan son min-width: tablet breakpoint, min-width: desktop breakpoint y min-width: large-screen breakpoint. 

Así como lo tenés es un estilo pensado para desktop adaptado a mobile, la consigna lo pide al revés.

Por otro lado fijate que hay variables declaradas en el archivo global para los breakpoints. Si los que tenés que usar no están declaralos y utilizalos acá. 

Por último, las media queries deberían estar anidadas en cada clase que las tengas que usar y no hacer una media querie grande redeclarando las clases que ya existen. Se repite menos código.

2021-12-15 14:48 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
> +    .campaign__{
misma corrección

2021-12-15 14:48 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
> +    .campaign__{
misma corrección

2021-12-17 04:43 UTC, FlaviaCohen requested changes

2021-12-17 04:43 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
>      .campaign__{
recordá lo que expliqué hoy de no declarar una media query con todas las clases adentro sino que deberíamos declarar en cada clase las media queries necesarias para ajustar el estilo. Entonces lo que se va a repetir son las media queries pero no las clases

2021-12-17 04:43 UTC, FlaviaCohen commented on src/styles/components/schoolCampaignStyles.scss
>  .campaign__{
Es decir que las media queries deberían estar en este archivo, dentro de cada clase

2021-12-17 04:43 UTC, FlaviaCohen commented on src/Components/Header/Header.jsx
> +
Esto ya lo corregí en la tarea 126, respetemos lo que charlamos hoy de no crear branches desde una branch con trabajo incompleto sino desde main

2021-12-17 04:43 UTC, FlaviaCohen commented on src/Components/Header/SideBar.js
> +  return (
Mismo comentario

2021-12-17 04:43 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +      setLoading(false)
mismo comentario

2021-12-17 04:43 UTC, FlaviaCohen commented on src/styles/components/backofficeNavStyles.scss
> +    &aside{
si estás usando un selector como aside o nav no es necesario poner el & ya que este concatena nombres de clases. 

Esto
```
.backoffice__{
    &aside{
        ....
    }
}
```
es lo mismo que esto:
```
.backoffice__{
    ...
}

.backoffice__ aside{
    ....
}
```
La forma correcta sería esta: 

```
.backoffice{
    aside{
        ....
    }
}
```

2021-12-17 04:43 UTC, FlaviaCohen commented on src/styles/components/backofficeNavStyles.scss
> +    &item{
Otro detalle es que los guión bajo no se dejan en el padre sino en el hijo, por eso la forma de anidar correctamente es esta: 

```
.bloque {
    &__elemento{
        &-modificador{
        ...
        }
    }
}
```

2021-12-18 20:03 UTC, FlaviaCohen approved these changes

2021-12-18 20:03 UTC, merged