Ot103 109
alkemyTech/OT103-Client pull request #114
Opened 2021-12-14 00:53 UTC by guidoFortunato

2021-12-14 02:57 UTC, FlaviaCohen requested changes

2021-12-14 02:57 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +  }, [loadApiData]);
cual es el motivo de tener loadApiData en el array del useEffect? 
Lo que hace ese array es recibir un estado al que va a estar "escuchando" y en el caso de que ese estado cambie volverá a ejecutar lo que esté dentro de la función que se le pasa como primer parámetro. En este caso ese loadApiData en el array no está haciendo nada.

2021-12-14 05:41 UTC, guidoFortunato commented on src/Components/News/NewsForm.js
> +  }, [loadApiData]);
lo puse porque me aparecía el warning de que faltaba esa dependencia

2021-12-15 15:04 UTC, FlaviaCohen approved these changes

2021-12-15 15:04 UTC, merged