[OT103-133]
alkemyTech/OT103-Client pull request #116
Opened 2021-12-14 21:25 UTC by JulianKominovic

**Tarea: Estructurar componente Footer**

2021-12-15 02:59 UTC, FlaviaCohen requested changes

2021-12-15 02:59 UTC, FlaviaCohen commented on src/Campaigns/School/Footer.jsx
> +import somosMasLogo from "../../assets/images/logo.png";
Excelente el uso del método BEM en este archivo, lo entendiste re bien Juli!

2021-12-15 02:59 UTC, FlaviaCohen commented on src/styles/components/footerStyles.scss
> +  & .footer__social {
Esta clase .footer__social iriía sin el "&" ya que al estar anidado es lo mismo que en CSS declarar 

```
.school__footer > .footer__social {
    ...
}
```
Por otro lado esa clase .footer podría contener de forma anidada a &__social, &__logo y &__campaigns.

Si te marea anidar tanto pueden declararse los bloques por separado, es decir, no anidados. También fijate que el vscode te da la posibilidad de cerrar código que está en el mismo nivel para poder verlo más claro. Eso puede ayudar

2021-12-15 02:59 UTC, FlaviaCohen commented on src/styles/media-querys/mediaFooter.scss
> +@media screen and (min-width: 767px) {
No es necesario que estos estilos estén en un archivo aparte. De hecho es mejor que estén en el mismo documento ya que sino se hace dificil debuggear el estilo. 

Por otro lado es conveniente declarar las media queries anidadas en las clases y no declarar una media query con todas las clases adentro.

2021-12-15 02:59 UTC, FlaviaCohen commented on src/styles/media-querys/mediaFooter.scss
> +  .school__footer {
Por último fijate que en el proyecto ya hay clases declaradas para algunos breakpoints. Si los que vos usas no están deberías declararlos en el archivo general de estilo y utilizarlos.

2021-12-15 15:15 UTC, JulianKominovic commented on src/styles/media-querys/mediaFooter.scss
> +  .school__footer {
Me fije, pero no son breakpoints de mobile first y no eran medidas estandares, asique hice unos nuevos.

Tendria que reestructurar todo el css si uso esos breakpoints.

2021-12-15 15:34 UTC, JulianKominovic commented
errores corregidos

2021-12-16 03:36 UTC, FlaviaCohen requested changes

2021-12-16 03:36 UTC, FlaviaCohen commented on src/styles/components/footerStyles.scss
> +  @media screen and (min-width: 1024px) {
Excelentes correcciones. Solo faltaría declarar variables para estos breakpoints si es que no existen ya que tus compañeros van a tener que usarlas también.

2021-12-18 17:50 UTC, JulianKominovic commented
Arreglado

2021-12-18 20:10 UTC, FlaviaCohen requested changes

2021-12-18 20:10 UTC, FlaviaCohen commented on src/Campaigns/Toys/ToysCampaing.scss
> +@media screen and (min-width: $breakpoint-tablet) {
Esto lo hiciste vos juli o te lo trajiste del main? 

Porque esta media query debería estar anidada en las clases, no las clases dentro de la media query

2021-12-18 20:10 UTC, FlaviaCohen commented on src/Components/Footer/Footer.scss
> +    @media (min-width: 578px){
Hay forma de que estos breakpoints los declares en variables en el archivo donde están todas las variables de sass? 

Tal vez ya haya algún breakpoint declarado que puedas reutilizar, y sino dejás disponibles estos nuevos para tus compañeros

2021-12-18 20:10 UTC, FlaviaCohen commented on src/Components/Footer/Footer.scss
> +    @media (min-width: 578px){
Solucionar conflictos

2021-12-18 20:43 UTC, JulianKominovic commented on src/Campaigns/Toys/ToysCampaing.scss
> +@media screen and (min-width: $breakpoint-tablet) {
No es mio eso Fla, me lo traje del main

2021-12-18 20:43 UTC, JulianKominovic commented on src/Components/Footer/Footer.scss
> +    @media (min-width: 578px){
Ese footer tampoco es mio

2021-12-20 00:13 UTC, JulianKominovic commented
Arreglado

2021-12-21 00:52 UTC, FlaviaCohen approved these changes

2021-12-21 00:52 UTC, merged