Ot103 126
alkemyTech/OT103-Client pull request #123
Opened 2021-12-16 00:02 UTC by decdabo

Header with links in backoffice

2021-12-16 03:25 UTC, FlaviaCohen requested changes

2021-12-16 03:25 UTC, FlaviaCohen commented on src/Campaigns/School/Footer.js
> +    <footer className="HS-campaign__footer-container">
Esto ya lo habíamos corregido en el otro PR. Ojo! Cuando una branch sale de otra antes de que esa esté terminada asegurate de hacer pull del main.

2021-12-16 03:25 UTC, FlaviaCohen commented on src/Campaigns/School/Header.js
> +    <header className="HS-campaign__header-container">
misma correción

2021-12-16 03:25 UTC, FlaviaCohen commented on src/Campaigns/School/Slider.js
> +    <div className='HS-campaign__slider-container'>
misma corrección

2021-12-16 03:25 UTC, FlaviaCohen commented on src/Services/serviceSlide/servicesSlide.js
> +
este archivo lo creaste vos? Para que sería?

2021-12-16 03:25 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +      setLoading(null);
el valor correcto de setLoading en este caso sería false, no null ya que sino estarías mezclando tipos de datos. 

Booleanos = true o false
null y undefined son tipos de datos false pero no deberían mezclarse con booleanos solo por eso.

2021-12-16 03:25 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +      setLoading(true);
acá el loading nunca vuelve a setearse en false. Cuando deja de loadear?

2021-12-16 03:25 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
>      getData();
Declararía el useEffect así: 

```
useEffect(() => {
    arrayData ? setData(arrayData) : getData()
})
```

De esta manera te ahorrás el ternario en el jsx y no repetís código.. que quedaría así: 

`return loading ? <LoaderComponent /> : data.map( slide => <SlideComponent key={obj.id} data={obj} height={height} /> )`

2021-12-16 03:25 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
>      getData();
Y en la línea 35 es más simple que la condición del ternario sea directamente` loading ? ` ya que va a ser true o false (aún siendo null, ese tipo de dato es false)

2021-12-16 03:25 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
> +@media (max-width: 500px){
Misma corrección que el otro PR

2021-12-16 03:25 UTC, FlaviaCohen commented on src/styles/components/schoolCampaignStyles.scss
> +    &container{
Misma corrección

2021-12-16 08:56 UTC, decdabo commented on src/Campaigns/School/Header.js
> +    <header className="HS-campaign__header-container">
pero se supone que esto no lo tenés que corregir porque esto es de otro PR, cualquier cosa hago el pull y lo corrijo en la otra branch :(

2021-12-16 08:57 UTC, decdabo commented on src/styles/components/schoolCampaignStyles.scss
> +    &container{
pero no me correjiste nada de esta branch al final jajajaja

2021-12-16 09:05 UTC, decdabo commented on src/Services/serviceSlide/servicesSlide.js
> +
Este archivo no lo cree yo, era para el users si no me equivoco, igualmente no se usa ya este componente.

2021-12-16 15:06 UTC, FlaviaCohen requested changes

2021-12-16 15:06 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
>    const [loading, setLoading] = useState(false);
Esto estaba arreglado, no se porque volvió a este estado. Fijate que el estado inicial de loading debe ser true

2021-12-16 15:06 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +        {loading ?
al revés... `loading ?` significa` loading == true` entonces `loading ? <LoaderComponent /> : (data.map(obj => { return <SlideComponent key={obj.id} data={obj} height={height} /> }))`

2021-12-16 23:00 UTC, FlaviaCohen requested changes

2021-12-16 23:00 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +    if (arrayData) {
Si vas a separar esto en un método como hiciste podés poner el setLoading(false) al final, después del condicional y lo borrás del getData. 

Sino queda raro que esté en un lugar y en otro no, es confuso.

2021-12-16 23:00 UTC, FlaviaCohen commented on src/styles/components/mediaSchoolCampaign.scss
>      .HS-campaign__content-{
Vamos de nuevo con las correcciones del estilo mobile-first. 

1.- Las media queries deben ser de tipo min-width ya que el estilo por default debe ser el de mobile. 
2.- Las media queries tienen que estar dentro de las clases para no repetirlas, no repetir las clases dentro de cada media query.
3.- Habíamos quedado en que ese HS de la clase no iba, solo campaign. Primero porque HS es por high school que significa secundaria y segundo porque los estilos de campaign deberían ser reutilizables para todas las campañas entonces no tiene sentido que haya un estilo para campaña escolar y otra para juguetes.

2021-12-17 00:02 UTC, FlaviaCohen requested changes

2021-12-17 00:02 UTC, FlaviaCohen commented on src/Components/Header/Header.jsx
> +    const [open, setOpen] = useState(-100);
open debería ser un booleano, true para open y false para close

2021-12-17 00:02 UTC, FlaviaCohen commented on src/Services/serviceSlide/servicesSlide.js
> +
Pero en main no está. Si no se usa hay que borrarlo.

2021-12-17 00:02 UTC, FlaviaCohen commented on src/slideHome/SlideComponent.js
>          <div style={{
De nuevo... clase en vez de atributo style

2021-12-17 00:02 UTC, FlaviaCohen commented on src/Components/Header/SideBar.js
> +    <aside className="backoffice__aside" style={{ left: `${left}%` }}>
y acá en vez de poner un estilo inline podemos poner un atributo className con un condicional entre dos clases "open" y "close" con sus respectivos estilos

2021-12-17 00:02 UTC, FlaviaCohen commented on src/slideHome/SliderCarouselComponent.js
> +      setLoading(false);
vamos de nuevo. Podés hacer esto: 

```
const validation = () => {
    if (arrayData) {
        setData(arrayData)
    } else {
        getData();
   }
    setLoading(false);
}
```
La idea es no repetir código

2021-12-18 19:54 UTC, FlaviaCohen requested changes

2021-12-18 19:54 UTC, FlaviaCohen commented on src/Components/Header/Header.jsx
> +        if(open){
Hay una forma más resumida de hacer esto, es un método que se llama "toggle". Sería así:

`onClick={ () => setOpen(!open)}`

De esta forma si open es true lo cambia a false y si es false lo cambia a true. Lo vas a usar mucho.

2021-12-18 19:54 UTC, FlaviaCohen commented on src/Components/Header/SideBar.js
> +    if(isOpen){
esto en vez de tenerlo acá podrías tenerlo directamente dentro de la clase como un condicional.

2021-12-18 19:54 UTC, FlaviaCohen commented on src/Components/Header/SideBar.js
> +    <aside className={`aside ${statusNav}`} >
`<aside className={`aside ${isOpen ? "openNav" : "closeNav"}`} >`

2021-12-19 16:05 UTC, FlaviaCohen approved these changes

2021-12-19 16:05 UTC, merged