[OT103-33] Feat
alkemyTech/OT103-Client pull request #13
Opened 2021-11-25 16:47 UTC by nahueldefazio

Agrego componente reutilizable para la creacion y edicion de usuarios

2021-11-25 22:34 UTC, FlaviaCohen requested changes

2021-11-25 22:34 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +                                        onChange={(event) => {
Tratamos de no poner mucha lógica dentro del código JSX, en tal caso es una mejor práctica declarar una función handleChange antes de retornar el JSX y llamarla dentro del onChange.

2021-11-26 13:34 UTC, nahueldefazio commented on src/Components/Users/UsersForm.js
> +                                        onChange={(event) => {
Resuelto

2021-11-28 02:44 UTC, FlaviaCohen requested changes

2021-11-28 02:44 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +                name: values.name,
No es necesario declarar un objecto nuevo. Se puede hacer directamente así:

`axios.post(`${url}`, values)`

2021-11-28 02:44 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +            axios.put(`${url}/${id}`, {
Lo mismo acá

2021-11-28 02:44 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +                setName(response.data.data.name)
Y acá podemos desestructurar un poco para no repetir tantas veces response.data.data. Quedaría así: 

```
const {data: {data: {name, email, role_id, password}}
setName(name)
setEmail(email)
setPassword(password)
```

2021-11-29 00:12 UTC, FlaviaCohen approved these changes

2021-11-29 00:12 UTC, merged