Routes fix
alkemyTech/OT103-Client pull request #147
Opened 2021-12-22 23:37 UTC by JulianKominovic

2021-12-24 02:23 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-26 18:12 UTC, FlaviaCohen requested changes
Solucionar conflicto

2021-12-26 22:24 UTC, JulianKominovic commented
Conflictos arreglados

2021-12-27 14:41 UTC, FlaviaCohen approved these changes

2021-12-27 14:41 UTC, merged