[OT103]-166
alkemyTech/OT103-Client pull request #152
Opened 2021-12-23 19:39 UTC by decdabo

Searcher component para el manage activities además de componentizar y manejo de errores en caso de no encontrar nada

2021-12-24 00:43 UTC, FlaviaCohen requested changes

2021-12-24 00:43 UTC, FlaviaCohen commented on src/Components/ManageActivities/ActivityItem.js
> +        <tr>
Ya habíamos hablado de que los tags que corresponden a elementos de tabla no deben utilizarse fuera de un tag <table />. Mejor usar divs si no vas a usar la estructura completa de la tabla.

2021-12-24 00:43 UTC, FlaviaCohen commented on src/Components/ManageActivities/ActivityItem.js
> +            <td className="activity-table-data">{activity.name}</td>
acordate de usar el método BEM para nombrar clases

2021-12-24 00:43 UTC, FlaviaCohen commented on src/Components/ManageActivities/SearchActivities.js
> +            console.log(error)
Acá podés reutilizar el componente para manejar errores AlertError

2021-12-24 00:43 UTC, FlaviaCohen commented on src/Components/ManageActivities/SearchActivities.js
> +                .catch(e => console.log(e));
acá también

2021-12-24 00:53 UTC, decdabo commented on src/Components/ManageActivities/ActivityItem.js
> +            <td className="activity-table-data">{activity.name}</td>
Esto no lo hice yo, pero lo puedo hacer ya que estoy (?

2021-12-24 00:54 UTC, decdabo commented on src/Components/ManageActivities/ActivityItem.js
> +        <tr>
No lo hice yo a esto, simplemente componenticé algo que hizo mi compañero pero lo hago

2021-12-26 18:03 UTC, FlaviaCohen requested changes

2021-12-26 18:03 UTC, FlaviaCohen commented on src/Components/ManageActivities/ManageActivities.js
>  	const [editingActivity, setEditingActivity] = useState(NaN); // will change to the id of the activity to edit
Si el tipo de dato es "number" el estado inicial debería ser 0

2021-12-26 18:03 UTC, FlaviaCohen commented on src/Components/ManageActivities/ActivityItem.js
> +        <tr>
mmm... sabés quien lo hizo? así le digo que lo arregle

2021-12-26 22:36 UTC, FlaviaCohen requested changes

2021-12-26 22:36 UTC, FlaviaCohen commented on src/Components/ManageActivities/ManageActivities.js
> +  const [editingActivity, setEditingActivity] = useState(NaN); // will change to the id of the activity to edit
De nuevo, si este estado a futuro será un dato de tipo number debe inicializar en 0, NaN no es el mismo tipo de dato.

2021-12-27 14:19 UTC, FlaviaCohen approved these changes

2021-12-27 14:19 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.test.js
> +        console.log(nameInput)
Este console.log hay que borrarlo

2021-12-27 14:19 UTC, merged