[OT103-142] Feat
alkemyTech/OT103-Client pull request #163
Opened 2021-12-26 21:21 UTC by FaustoRossi

2021-12-26 22:27 UTC, FlaviaCohen requested changes

2021-12-26 22:27 UTC, FlaviaCohen commented on src/Components/Header/Header.jsx
> +				</button>n
Ojo que acá hay un error de tipeo, esa "n"

2021-12-26 22:46 UTC, FaustoRossi commented
parece que confundi las ramas, esta tendria que tener lo de Donate y la otra de school campaign

2021-12-27 14:20 UTC, FlaviaCohen approved these changes

2021-12-27 14:20 UTC, merged