[OT103-50] Feat
alkemyTech/OT103-Client pull request #18
Opened 2021-11-25 22:11 UTC by JulianKominovic

Ahi subo el componente para renderizar la INFO de actividades especificas.

**En la carpeta helpers** ademas agrego una funcion simple que transforma de fecha que viene desde la API a un objeto que te devuelve la fecha y la hora.

2021-11-25 23:16 UTC, FlaviaCohen requested changes

2021-11-25 23:16 UTC, FlaviaCohen commented on src/Components/Activities/Activities.scss
> +  flex: {
acá lo correcto sería que el estilo fuera así: 

`flex-direction: column;`

No hace falta abrir nuevamente llaves

2021-11-25 23:16 UTC, FlaviaCohen commented on src/Components/Activities/Activities.scss
> +* {
Este selector por convención siempre va al principio del documento y hay que usarlo con precausión ya que impacta en todo el sitio. Es preferible que le pongas un div con una clase container a tu componente y no que utilices ese selector para evitar colisiones.

2021-11-25 23:16 UTC, FlaviaCohen commented on src/Components/Activities/Activities.scss
> +    & footer {
Esto está mal anidado. Lo que estás declarando con esta anidación es que el estilo de footer aplica para todos los elementos footer que se encuentren dentro del elemento con clase .list__item (en este caso ninguno). Vos tenés un tag footer por fuera del elemento que tiene la clase .list__item por ende no es necesario anidarlo. Ojo con eso!

Además el footer de una vista suele ser 1 solo y no es necesario anidarlo. Si tenés más de un tag footer sería una mala práctica de HTML. 
De hecho el tag footer suele ser 1 sólo en toda la página, hay un componente footer que se importa en App.js y se renderiza por fuera de las rutas para que sea común a todas las vistas (salvo que haya footers diferentes dependiendo de la vista, lo cual es raro pero posible).

2021-11-25 23:35 UTC, JulianKominovic commented on src/Components/Activities/Activities.scss
> +    & footer {
Joya, ya lo corrijo y lo subo, muchas gracias por la correccion!

2021-11-25 23:50 UTC, JulianKominovic commented
Errores corregidos! saludosss

2021-11-26 02:27 UTC, FlaviaCohen approved these changes, later dismissed

2021-11-26 02:28 UTC, FlaviaCohen requested changes
Hacer un pull de main y solucionar conflictos

2021-11-26 22:07 UTC, JulianKominovic commented
Main pulleado, tuve que sacar el App.js y deje el App.jsx con los imports que me correspondian + los anteriores.

2021-11-28 02:35 UTC, FlaviaCohen approved these changes, later dismissed

2021-11-28 23:44 UTC, JulianKominovic commented
Conflictos resueltos. Component TITLE integrado a componente Actividades y DetallesActividades.

2021-11-29 13:04 UTC, FlaviaCohen approved these changes

2021-11-29 13:04 UTC, merged