[OT103-51] Feat
alkemyTech/OT103-Client pull request #34
Opened 2021-11-30 21:47 UTC by nahueldefazio

Agregué la ruta "/home" con el componente HomeDashboard.jsx. En ese componente llamo a HomeCards para renderizar las cards. Cada componente tiene su CSS y agregue en el index.html los cdn de Bootstrap para darle un poco de estilo. Es temporal esos estilos, depues cuando hagamos la tarjeta de estilos con el team, los cambio

2021-12-01 02:34 UTC, FlaviaCohen requested changes

2021-12-01 02:34 UTC, FlaviaCohen commented on src/Components/HomeCards/HomeCards.jsx
> +        <div className="card m-2 text-center" style={ {width: "18rem "} }>
No usemos el atributo style para darle estilos de esta forma, es mala práctica. Mejor hacer un archivo de estilo aparte.

2021-12-01 12:57 UTC, FlaviaCohen requested changes

2021-12-01 12:57 UTC, FlaviaCohen commented on src/Components/HomeCards/HomeCards.css
> +.size{
Perdón por ser tan detallista pero este tipo de clases se llaman "utils" y son clases que sólamente agregan 1 línea de estilo y se nombran describiendo lo que hacen. Por ejemplo esta debería llamarse `.w-18r` (por "width 18 rem"). Se pueden agregar a un archivo de estilo que se llame utils.css o utils.scss y de esta manera todos pueden reutilizarla.

2021-12-02 16:21 UTC, FlaviaCohen requested changes

2021-12-02 16:21 UTC, FlaviaCohen commented on src/Components/HomeCards/HomeCards.jsx
> +        <div className="card m-2 text-center size w-18r">
la clase "size" ya no hace nada asi que hay que borrarla

2021-12-02 16:21 UTC, FlaviaCohen commented on src/App.jsx
> +          <Route path="/home" exact component={HomeDashboard}/>
la tarjeta pedía que se visualice al entrar a la ruta `"/backoffice"` ya que hay otra tarjeta que tiene la ruta para el home pública

2021-12-02 16:21 UTC, FlaviaCohen commented on src/Components/HomeDashboard/HomeDashboard.jsx
> +    const cardsInfo = [
Este array es un mock y debería estar en un archivo .json en la carpeta /lib/mock

2021-12-02 17:00 UTC, nahueldefazio commented on src/Components/HomeDashboard/HomeDashboard.jsx
> +    const cardsInfo = [
Hecho

2021-12-02 21:55 UTC, FlaviaCohen approved these changes

2021-12-02 21:56 UTC, merged