[OT103]-78
alkemyTech/OT103-Client pull request #41
Opened 2021-12-01 18:57 UTC by decdabo

Users services get update

2021-12-02 14:24 UTC, FlaviaCohen requested changes

2021-12-02 14:24 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +            alert('user inexistente');
mezcla de idiomas

2021-12-02 14:24 UTC, FlaviaCohen commented on src/Components/Users/UsersForm.js
> +        if(id){
Este condicional tendría que estar integrado en el método getData y en el useEffecto solo llamar al método.

2021-12-02 14:24 UTC, FlaviaCohen commented on src/backoffice/FormEditActivities.js
> +                    axios.post(linkApi, values)
No corresponde a tu tarjeta pero acá hay que usar el Post nuevo.

2021-12-02 14:24 UTC, FlaviaCohen commented on src/backoffice/SlidesScreen/ItemList.js
> +    const handleDelete = async() => {
Reutilizar metodo delete

2021-12-02 14:24 UTC, FlaviaCohen commented on src/slideHome/SliderApp.js
> +export const SliderApp = ({ URL = 'http://ongapi.alkemy.org/api/slides', method='GET', arrayData }) => {
App es una palabra reservada muy precisa para describir donde se arma la aplicación. Buscaría un nombre más descriptivo para este componente como Carousel, Slides, SlidesCarousel.

2021-12-02 15:44 UTC, FlaviaCohen requested changes

2021-12-02 15:44 UTC, FlaviaCohen commented on src/backoffice/FormEditActivities.js
> +    const handleSend = async (values) => {
super hincha lo mio pero "handleSubmit" es un nombre más descriptivo

2021-12-02 15:44 UTC, FlaviaCohen commented on src/backoffice/FormEditActivities/FormEditData.js
> +    const handleSend = async (values) => {
Lo mismo acá

2021-12-02 15:45 UTC, decdabo commented on src/backoffice/FormEditActivities.js
> +    const handleSend = async (values) => {
Pasa que handleSubmit ya está siendo usado en el Formik, esto sería lo que se ejecuta en el handleSubmit

2021-12-02 15:48 UTC, FlaviaCohen submitted a review, later dismissed

2021-12-02 22:11 UTC, FlaviaCohen submitted a review, later dismissed

2021-12-02 22:11 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-03 01:16 UTC, FlaviaCohen approved these changes, later dismissed

2021-12-03 01:17 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-04 15:19 UTC, FlaviaCohen approved these changes

2021-12-04 15:19 UTC, merged