[OT103-61] Feat
alkemyTech/OT103-Client pull request #47
Opened 2021-12-02 18:32 UTC by JulianKominovic

Terminada esta tarea:
Screen Listado de Novedades (backoffice)

2021-12-02 22:24 UTC, FlaviaCohen submitted a review, later dismissed

2021-12-02 22:25 UTC, FlaviaCohen requested changes
Resolver conflictos

2021-12-03 14:21 UTC, JulianKominovic commented
Conflictos corregidos!

2021-12-03 15:53 UTC, FlaviaCohen approved these changes, later dismissed

2021-12-03 15:54 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-05 22:31 UTC, JulianKominovic commented
Estilos aplicados y componente terminado.

2021-12-05 23:59 UTC, FlaviaCohen requested changes

2021-12-05 23:59 UTC, FlaviaCohen commented on src/Components/News/NewsItem.jsx
> +      <img className="list__item-image" src={image} alt={name} />
en vez de repetir tantas veces la palabra "item" el bloque debería llamarse item y el resto son los elementos. 

```
item__image
item__group
item__title
```
etc

2021-12-05 23:59 UTC, FlaviaCohen commented on src/styles/components/listStyles.scss
> +  &__item {
la idea de la corrección que te hice anteriormente es, además de repetir menos código, ser más descriptivos. En este caso el bloque es el item, la palabra list hace referencia a un componente padre que no vendría al caso. No estoy segura de si la clase .list sola se utiliza en otro documento pero en este caso el bloque sigue siendo item y a lo sumo podés utilizar una clase .item__container para usar de wrapper si la necesitás.

2021-12-06 17:38 UTC, JulianKominovic commented
Arreglado!

2021-12-06 18:41 UTC, FlaviaCohen approved these changes

2021-12-06 18:41 UTC, merged