[OT103-76] Feat
alkemyTech/OT103-Client pull request #48
Opened 2021-12-02 19:11 UTC by JulianKominovic

Terminada esta tarea:
Extender servicio HTTP base para las peticiones de Novedades.

2021-12-02 22:16 UTC, FlaviaCohen requested changes

2021-12-02 22:16 UTC, FlaviaCohen commented on src/Components/News/NewsList.js
> +              <NewsItemList {...element} key={element.id} setNews={setNews} />
Si NewsItemList es un componente <li></li> debería llamarse <NewsItem/> porque en esencia es un Item, no una lista. De esta forma sería más descriptivo

2021-12-03 14:19 UTC, JulianKominovic commented
Errores corregidos!

2021-12-03 15:52 UTC, FlaviaCohen approved these changes

2021-12-03 15:52 UTC, merged