[OT103-28] Feat
alkemyTech/OT103-Client pull request #6
Opened 2021-11-24 20:20 UTC by JulianKominovic

Elimine lo que quedaba del boilerplate de Redux, logo, el contador de ejemplo, etc...
Progreso:
Funcionamiento minimo: ✅
Estilos: (demorado hasta tener definido el estilo global)
Interaccion con api:  ✅
Testeo:  (no se pudo hacer por cause de la libreria CKEditor5)
Integracion con el proyecto:✅

2021-11-24 23:49 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.jsx
> +          console.log(values);
Digale NO a los console.logs en un PR :)

2021-11-24 23:50 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.test.js
> +import { render } from "@testing-library/react";
No vamos a hacer tests por ahora así que mejor borrar este archivo

2021-11-24 23:54 UTC, FlaviaCohen commented on src/Services/privateApi/categoryApi.test.js
> +// });
lo mismo para este archivo, mejor borrarlo

2021-11-24 23:57 UTC, FlaviaCohen requested changes

2021-11-24 23:57 UTC, FlaviaCohen commented on src/index.js
> +<<<<<<< HEAD
esto es un conflicto?

2021-11-25 01:09 UTC, JulianKominovic commented on src/Components/Categories/CategoriesForm.jsx
> +          console.log(values);
✅

2021-11-25 01:09 UTC, JulianKominovic commented on src/Components/Categories/CategoriesForm.test.js
> +import { render } from "@testing-library/react";
✅

2021-11-25 01:09 UTC, JulianKominovic commented on src/Services/privateApi/categoryApi.test.js
> +// });
✅

2021-11-25 01:09 UTC, JulianKominovic commented on src/index.js
> +<<<<<<< HEAD
✅

2021-11-25 01:10 UTC, JulianKominovic commented
Errores corregidos!

2021-11-25 02:25 UTC, FlaviaCohen approved these changes

2021-11-25 02:25 UTC, merged