[OT103-106] Feat
alkemyTech/OT103-Client pull request #83
Opened 2021-12-08 16:31 UTC by JulianKominovic

Reducer, actions y custom hook terminados.

2021-12-08 20:56 UTC, FlaviaCohen submitted a review, later dismissed

2021-12-08 20:57 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-08 21:27 UTC, JulianKominovic commented
Conflictos solucionados!

2021-12-09 13:50 UTC, FlaviaCohen approved these changes

2021-12-09 13:50 UTC, merged