[OT103-47] Feat
alkemyTech/OT103-Client pull request #84
Opened 2021-12-08 18:36 UTC by JulianKominovic

Estilos aplicados a las tarjetas:

- OT103-50
- OT103-61
- OT103-57
- OT103-28

2021-12-08 20:50 UTC, FlaviaCohen requested changes

2021-12-08 20:50 UTC, FlaviaCohen commented on src/Components/Members/MembersEdit.scss
> +// @import "../../styles//variables.scss";
Todo esto quedó comentado porque lo vas a utilizar más tarde? Sino lo borraría

2021-12-08 21:00 UTC, JulianKominovic commented on src/Components/Members/MembersEdit.scss
> +// @import "../../styles//variables.scss";
Eso no es mio, lo tuve que comentar porque me daba problemas, y no queria borrarlo porque no lo escribi yo, ademas sino me equivoco archivos como este se deberian borrar como acordamos, si me permitis, aviso al grupo y borro todos los estilos que no correspondan.

2021-12-08 21:30 UTC, JulianKominovic commented
Conflictos solucionados, esperando respuesta al cambio solicitado.

2021-12-09 13:41 UTC, FlaviaCohen approved these changes

2021-12-09 13:43 UTC, FlaviaCohen requested changes
Resolver conflictos

2021-12-10 14:06 UTC, JulianKominovic commented
Conflictos resueltos!

2021-12-10 14:26 UTC, FlaviaCohen requested changes
Solucionar conflictos

2021-12-10 14:51 UTC, JulianKominovic commented
Conflictos arreglados!

2021-12-10 16:21 UTC, FlaviaCohen approved these changes

2021-12-10 16:21 UTC, merged