[OT103-85] Feat
alkemyTech/OT103-Client pull request #86
Opened 2021-12-08 21:46 UTC by JulianKominovic

Endpoints actualizados y .env creado.

2021-12-09 14:02 UTC, FlaviaCohen requested changes

2021-12-09 14:02 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +    <div className="activities-list">
Debería ser .activities__list

2021-12-09 14:03 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesList.jsx
> +    <div className="activities-list">
Resolver conflictos

2021-12-10 13:43 UTC, JulianKominovic commented
Conflictos solucionados y todo arreglado!

2021-12-10 14:22 UTC, FlaviaCohen approved these changes

2021-12-10 14:22 UTC, merged